WORLD_NAME: world

#Main Settings
TEAM_SIZE: 4
MAX_PLAYERS: 16
PLAYERS_TO_COUNTDOWN: 2

#team spawns
SPAWN:
  RED:
    X: 0.5
    Y: 80.0
    Z: -25.5
    YAW: 0.0
  GREEN:
    X: 25.5
    Y: 80.0
    Z: 0.5
    YAW: 90.0
  BLUE:
    X: 0.5
    Y: 80.0
    Z: 25.5
    YAW: 180.0
  YELLOW:
    X: -25.5
    Y: 80.0
    Z: 0.5
    YAW: -90.0
#team beds
BED:
  RED:
    X: 0
    Y: 80
    Z: -21
  GREEN:
    X: 21
    Y: 80
    Z: 0
  BLUE:
    X: 0
    Y: 80
    Z: 21
  YELLOW:
    X: -21
    Y: 80
    Z: 0

#map
MAP:
  CENTER:  #deathspawn
    X: 0.5
    Y: 95.0
    Z: 0.5
  LOBBY:
    X: 4.5
    Y: 80.0
    Z: 4.5

#Y == leg position!!!!
#diamonds - any amount
DIAMOND:
  D1:
    X: 15.5
    Y: 80.0
    Z: 15.5
  D2:
    X: -14.5
    Y: 80.0
    Z: 15.5
  D3:
    X: 15.5
    Y: 80.0
    Z: -14.5
  D4:
    X: -14.5
    Y: 80.0
    Z: -14.5

#emeralds - any amount
EMERALD:
  E1:
    X: 0.5
    Y: 80.0
    Z: 0.5

FURNACE:
  RED:
    X: -1.5
    Y: 80.0
    Z: 7.5


#Messages
  #Commands
    #Team
TEAM_CMD_ERROR_BAD_USAGE: §4Poprawne uzycie /team red, blue, yellow, green
TEAM_CMD_ERROR_NOT_ALLOWED: §4Nie możesz użyć tej komendy
TEAM_JOINED: §3Dolaczyles do Team %team%
    #BedWars
BED_WARS_CMD_ERROR_BAD_USAGE: §4Poprawne uzycie uj wi jak xDD
    #all
CMD_ERROR_NO_ACCESS: §4Nie masz uprawnien


PLAYER_JOINED: §2%player% dolaczyl
BED_DESTROYED: §2%player% zniszczyl lozko teamu %team%
PLAYER_LEFT: §2%player% wyszedl
COUNTDOWN_PAUSED: §4Uwaga odliczanie wstrzymane - za malo graczy
PLAYER_RESPAWN_IN_5: §2Uwaga odrodzisz sie za 5 sekund
